// US cities formatted as "City, ST" — top ~300 by population, suitable for autocomplete
const US_CITIES = [
  'New York, NY', 'Los Angeles, CA', 'Chicago, IL', 'Houston, TX', 'Phoenix, AZ',
  'Philadelphia, PA', 'San Antonio, TX', 'San Diego, CA', 'Dallas, TX', 'San Jose, CA',
  'Austin, TX', 'Jacksonville, FL', 'Fort Worth, TX', 'Columbus, OH', 'Charlotte, NC',
  'Indianapolis, IN', 'San Francisco, CA', 'Seattle, WA', 'Denver, CO', 'Nashville, TN',
  'Oklahoma City, OK', 'El Paso, TX', 'Washington, DC', 'Las Vegas, NV', 'Louisville, KY',
  'Memphis, TN', 'Portland, OR', 'Baltimore, MD', 'Milwaukee, WI', 'Albuquerque, NM',
  'Tucson, AZ', 'Fresno, CA', 'Sacramento, CA', 'Mesa, AZ', 'Kansas City, MO',
  'Atlanta, GA', 'Omaha, NE', 'Colorado Springs, CO', 'Raleigh, NC', 'Long Beach, CA',
  'Virginia Beach, VA', 'Minneapolis, MN', 'Tampa, FL', 'New Orleans, LA', 'Arlington, TX',
  'Wichita, KS', 'Bakersfield, CA', 'Aurora, CO', 'Anaheim, CA', 'Santa Ana, CA',
  'Corpus Christi, TX', 'Riverside, CA', 'St. Louis, MO', 'Lexington, KY', 'Pittsburgh, PA',
  'Stockton, CA', 'Anchorage, AK', 'Cincinnati, OH', 'St. Paul, MN', 'Greensboro, NC',
  'Toledo, OH', 'Newark, NJ', 'Plano, TX', 'Henderson, NV', 'Orlando, FL',
  'Lincoln, NE', 'Jersey City, NJ', 'Chandler, AZ', 'St. Petersburg, FL', 'Laredo, TX',
  'Norfolk, VA', 'Madison, WI', 'Durham, NC', 'Lubbock, TX', 'Winston-Salem, NC',
  'Garland, TX', 'Glendale, AZ', 'Hialeah, FL', 'Reno, NV', 'Baton Rouge, LA',
  'Irvine, CA', 'Chesapeake, VA', 'Irving, TX', 'Scottsdale, AZ', 'North Las Vegas, NV',
  'Fremont, CA', 'Gilbert, AZ', 'San Bernardino, CA', 'Birmingham, AL', 'Boise, ID',
  'Rochester, NY', 'Richmond, VA', 'Spokane, WA', 'Des Moines, IA', 'Montgomery, AL',
  'Modesto, CA', 'Fayetteville, NC', 'Tacoma, WA', 'Shreveport, LA', 'Fontana, CA',
  'Glendale, CA', 'Akron, OH', 'Aurora, IL', 'Yonkers, NY', 'Columbus, GA',
  'Moreno Valley, CA', 'Huntington Beach, CA', 'Little Rock, AR', 'Glendale, CA',
  'Salt Lake City, UT', 'Grand Rapids, MI', 'Tallahassee, FL', 'Huntsville, AL',
  'Worcester, MA', 'Knoxville, TN', 'Brownsville, TX', 'Santa Clarita, CA', 'Providence, RI',
  'Garden Grove, CA', 'Oceanside, CA', 'Chattanooga, TN', 'Fort Lauderdale, FL',
  'Rancho Cucamonga, CA', 'Santa Rosa, CA', 'Port Arthur, TX', 'Tempe, AZ',
  'Cape Coral, FL', 'Ontario, CA', 'Vancouver, WA', 'Sioux Falls, SD', 'Peoria, AZ',
  'Springfield, MO', 'Elk Grove, CA', 'Pembroke Pines, FL', 'Corona, CA', 'Eugene, OR',
  'Salem, OR', 'Fort Collins, CO', 'Cary, NC', 'Jackson, MS', 'Alexandria, VA',
  'Hayward, CA', 'Lancaster, CA', 'Salinas, CA', 'Palmdale, CA', 'Sunnyvale, CA',
  'Pomona, CA', 'Escondido, CA', 'Kansas City, KS', 'Surprise, AZ', 'Paterson, NJ',
  'Rockford, IL', 'Torrance, CA', 'Bridgeport, CT', 'Hollywood, FL', 'Clarksville, TN',
  'Macon, GA', 'Killeen, TX', 'Syracuse, NY', 'Pasadena, TX', 'Mesquite, TX',
  'Metairie, LA', 'Savannah, GA', 'McKinney, TX', 'Bellevue, WA', 'Frisco, TX',
  'McAllen, TX', 'Denton, TX', 'Dayton, OH', 'Springfield, IL', 'Gainesville, FL',
  'Hampton, VA', 'Warren, MI', 'Columbia, SC', 'Miramar, FL', 'Coral Springs, FL',
  'Cedar Rapids, IA', 'Stamford, CT', 'Roseville, CA', 'Sterling Heights, MI',
  'Carrollton, TX', 'New Haven, CT', 'Topeka, KS', 'Hartford, CT', 'Thousand Oaks, CA',
  'Visalia, CA', 'Elizabeth, NJ', 'Concord, CA', 'Simi Valley, CA', 'Olathe, KS',
  'West Valley City, UT', 'Thornton, CO', 'Murfreesboro, TN', 'Columbia, MO',
  'Beaumont, TX', 'Lakewood, CO', 'Waterbury, CT', 'Independence, MO', 'Peoria, IL',
  'Arvada, CO', 'Ann Arbor, MI', 'Cambridge, MA', 'Clearwater, FL', 'West Palm Beach, FL',
  'Waco, TX', 'Fullerton, CA', 'Westminster, CO', 'Downey, CA', 'El Monte, CA',
  'Lansing, MI', 'Costa Mesa, CA', 'Miami Gardens, FL', 'Manchester, NH', 'Provo, UT',
  'Erie, PA', 'Odessa, TX', 'Midland, TX', 'Pompano Beach, FL', 'Inglewood, CA',
  'West Jordan, UT', 'Clovis, CA', 'Murrieta, CA', 'Round Rock, TX', 'Peoria, IL',
  'Temecula, CA', 'Antioch, CA', 'Norwalk, CA', 'Burbank, CA', 'High Point, NC',
  'Billings, MT', 'Pueblo, CO', 'West Covina, CA', 'Victorville, CA', 'Centennial, CO',
  'Everett, WA', 'Palm Bay, FL', 'Fargo, ND', 'Elgin, IL', 'Richmond, CA',
  'Glendale, CA', 'Jurupa Valley, CA', 'Lowell, MA', 'Athens, GA', 'Abilene, TX',
  'Wilmington, NC', 'Berkeley, CA', 'Flint, MI', 'Allentown, PA', 'Amarillo, TX',
  'Evansville, IN', 'Oxnard, CA', 'Peoria, AZ', 'South Bend, IN', 'Tallahassee, FL',
  'Rochester, MN', 'Gainesville, GA', 'Charleston, SC', 'Yuma, AZ', 'Laredo, TX',
  'Scottsdale, AZ', 'Shreveport, LA', 'Augusta, GA', 'Chattanooga, TN', 'Boise, ID',
  'Brooklyn, NY', 'Queens, NY', 'Manhattan, NY', 'The Bronx, NY', 'Staten Island, NY',
]

export default [...new Set(US_CITIES)].sort()
